redis:
  cache:
    - host:   192.168.0.100
      port:   6379
      db:     0
    - host:   192.168.0.100
      port:   6379
      db:     1
  disk:
    - host:   192.168.0.100
      port:   6380
      db:     0
    - host:   192.168.0.100
      port:   6380
      db:     1

memcache:
  - host:   192.168.0.101
    port:   11211
    expire: 60
  - host:   192.168.0.102
    port:   11211
    expire: 60

viewpath   : /home/www/templates/
serverpath : /home/www/server/